# Generated by Django 4.1.3 on 2023-01-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bonus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bonus_nomi", models.CharField(max_length=300)),
                ("bonus_miqdori", models.FloatField(max_length=1000)),
                ("bonus_muddati", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Bonus",
                "verbose_name_plural": "Bonuslar",
            },
        ),
        migrations.CreateModel(
            name="Hodim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ism_sharif", models.CharField(max_length=200)),
                ("lavozim", models.CharField(max_length=100)),
                ("stavka", models.FloatField()),
            ],
            options={
                "verbose_name": "Hodim",
                "verbose_name_plural": "Hodimlar",
            },
        ),
        migrations.CreateModel(
            name="Mahsulot_olchov",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("olchov", models.FloatField(help_text="(kg lik, litrlik ...)")),
                ("narx", models.FloatField(max_length=200)),
            ],
            options={
                "verbose_name": "Mahsulot o'lchovi",
                "verbose_name_plural": "Mahsulot o'lchovlari",
            },
        ),
        migrations.CreateModel(
            name="Mahsulotlar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mahsulot_rasm",
                    models.ImageField(
                        blank=True, null=True, upload_to="mahsulotlar/rasm"
                    ),
                ),
                ("mahsulot_nomi", models.CharField(max_length=200)),
                (
                    "mahsulot_format",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("dona", "dona"),
                            ("litr", "litr"),
                            ("metr", "metr"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mahsulot",
                "verbose_name_plural": "Mahsulotlar",
            },
        ),
        migrations.CreateModel(
            name="Mijoz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nomi", models.CharField(max_length=200)),
                ("ism_sharif", models.CharField(max_length=200)),
                ("telefon", models.CharField(max_length=19)),
                ("manzil", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Mijoz",
                "verbose_name_plural": "Mijozlar",
            },
        ),
        migrations.CreateModel(
            name="Ombor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("dona", "dona"),
                            ("litr", "litr"),
                            ("metr", "metr"),
                        ],
                        max_length=10,
                    ),
                ),
                ("narx", models.IntegerField()),
                ("miqdor", models.IntegerField()),
                ("izoh", models.TextField(blank=True, null=True)),
                (
                    "mahsulot_nomi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.mahsulotlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ombor",
                "verbose_name_plural": "Omborxona",
            },
        ),
        migrations.CreateModel(
            name="Import",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("dona", "dona"),
                            ("litr", "litr"),
                            ("metr", "metr"),
                        ],
                        max_length=10,
                    ),
                ),
                ("miqdor", models.IntegerField()),
                ("narx", models.IntegerField()),
                ("import_vaqt", models.DateTimeField()),
                ("izoh", models.TextField(blank=True, null=True)),
                (
                    "mahsulot_nomi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.mahsulotlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Import",
                "verbose_name_plural": "Import",
            },
        ),
        migrations.CreateModel(
            name="Export",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("kg", "kilogram"),
                            ("dona", "dona"),
                            ("litr", "litr"),
                            ("metr", "metr"),
                        ],
                        max_length=10,
                    ),
                ),
                ("miqdor", models.IntegerField()),
                ("narx", models.IntegerField()),
                ("export_vaqt", models.DateTimeField()),
                ("izoh", models.TextField(blank=True, null=True)),
                (
                    "mahsulot_nomi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.mahsulotlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Export",
                "verbose_name_plural": "Export",
            },
        ),
        migrations.CreateModel(
            name="Buyurtma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("kg", "kilogram"),
                            ("dona", "dona"),
                            ("litr", "litr"),
                            ("metr", "metr"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("miqdor", models.IntegerField()),
                ("buyurtma_sana", models.DateTimeField()),
                ("izoh", models.TextField(blank=True, null=True)),
                (
                    "buyurtma_nomi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyurtma",
                        to="app.mahsulotlar",
                    ),
                ),
                (
                    "buyurtma_olchov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="olchov_buyurtmasi",
                        to="app.mahsulot_olchov",
                    ),
                ),
                (
                    "mijoz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mijoz_buyurtmasi",
                        to="app.mijoz",
                    ),
                ),
                (
                    "narx",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="narx_buyurtmasi",
                        to="app.mahsulot_olchov",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
            },
        ),
    ]
