# Generated by Django 4.1.3 on 2023-01-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_mahsulotlar_mahsulot_narx_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mahsulotlar",
            name="mahsulot_narx",
        ),
        migrations.RemoveField(
            model_name="mahsulotlar",
            name="mahsulot_olchov",
        ),
        migrations.AddField(
            model_name="mahsulot_olchov",
            name="mahsulot",
            field=models.ManyToManyField(to="app.mahsulotlar"),
        ),
    ]
