# Generated by Django 4.0.5 on 2023-01-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_mahsulot_olchov_mahsulot_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot_olchov',
            name='mahsulot',
        ),
        migrations.AddField(
            model_name='mahsulot_olchov',
            name='mahsulot_number',
            field=models.IntegerField(default=0),
        ),
    ]
